### ISSUE TITLE
Fejlesztő környezet létrehozása

### ISSUE THREAD

**Issue by tanarurkerem** [drupalhu/drupal.hu#108]
Hogyan tudok helyi gépen fejlesztő környezetet létrehozni. Demo adatok, tesztek ilyenek.
Beszéljünk róla.

**Comment by aboros** [comment]
Légyszi tegyél javaslatot erre @tanarurkerem vagy zárjuk le akkor, ha jó ahogy most van. :)

**Comment by tanarurkerem** [comment]
Szerintem ez megvan.
