### ISSUE TITLE
Biztonsági frissítések kezelése

### ISSUE THREAD

**Issue by csakiistvan** [drupalhu/drupal.hu#172]
Drupal core (Biztonsági frissítés)	7.34	> 7.37
Entity API (Biztonsági frissítés)	7.x-1.5 > 7.x-1.6
Diff (Nem támogatott)	7.x-2.0 > 7.x-3.2
Webform (Biztonsági frissítés)	7.x-3.21 > 7.x-3.24
Chaos tool suite (ctools) (Biztonsági frissítés)	7.x-1.5 > 7.x-1.7
Views (Biztonsági frissítés)	7.x-3.8 > 7.x-3.11

**Comment by csakiistvan** [comment]
@snufkin úgy látom ezek kikerültek, lezárhatom az issuet?

**Comment by snufkin** [comment]
Igen

On Tuesday, June 9, 2015, Csáki István <notifications@github.com> wrote:

> @snufkin <https://github.com/snufkin> úgy látom ezek kikerültek,
> lezárhatom az issuet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drupalhu/drupal.hu/issues/172#issuecomment-110427466>.
>


-- 
Balazs Dianiska
Acquia EMEA PS Technical Architect
