### ISSUE TITLE
Email címre szűrés az oldalon

### ISSUE THREAD

**Issue by csakiistvan** [drupalhu/drupal.hu#175]
Meg kellene oldani hogy a user lista oldalon lehessen emialre keresni, mert elég macera így az embereket szűrni aki ír is az admin@ -ra, mert szemmel kell keresgélnem. Elsőre az admin_views modult javaslom, vagy egy sima paget viewsal ami teljesíteni ugyanazt amit az admin_views

**Comment by aboros** [comment]
admin_views modul +1

**Comment by snufkin** [comment]
Szerintem ez teljesen jo lesz igy elsore, nem erint semmit, toljad a PR-t. A View beallitasat deven meg kene csinalni es kitolni feature-be, es azzal egyutt lehet majd tesztelni masok altal is stage-en.

**Comment by csakiistvan** [comment]
megvalósult
