### ISSUE TITLE
"melyik modulhoz kapcsolódik" szótárat takarítani kéne

### ISSUE THREAD

**Issue by tanarurkerem** [drupalhu/drupal.hu#190]
Tele van mindenféle butasággal.

https://www.drupal.hu/admin/structure/taxonomy/vocabulary_11

Elvileg volt egy modul, ami csak azt engedte ami, de most már nem működk.
Javaslom valami script ami szinkronizálja a dorg-al a listát, és nem bővíthetővé tenni.

**Comment by Sweetchuck** [comment]
Ezzel kapcsolatban az alábbi észrevételeim vannak:

1. Ha modulhoz kapcsolódik a kérdés, akkor elég jó esélyjel meghatározható a Drupal core verziója is.
1. Jelenleg a "_Drupal verzió_" mező kitöltése nem kötelező és csak 1 érték választható.
1. Upgrade/migrate/backport feladatoknál 2 Drupal core verzió is érintett lehet. 6 -> 7, 6 - >8.
1. A "_Melyik modulhoz, modulokhoz kapcsolódik a téma?_" megengedett értékeinek függenie kéne a választott "_Drupal verzió_" mező értékétől.

Ha valaha szeretnénk rendes facet-es szűrést a fórumtémákra, akkor ezeket az adatokat konzisztens formában kéne tárolni.

**Comment by tanarurkerem** [comment]
Sweetchuck, minden egyes felvetéseddel egyetértek, de ez túl nagy falat lenne most. Én koncentrálnék a kitakarításra, és utána lehetne a verziókkal meg minden mással foglalkozni. 

pp

**Comment by tanarurkerem** [comment]
eheh.. rossz linket raktam be.. javítottam, így talán érthető, hogy mire gondolok, ha látjátok a sok csillagos szemetet.

**Comment by tanarurkerem** [comment]
Első körben lehet elég lenne kitoszni azokat a kategóriákat, amikhez nincs konkrét tartalom.

**Comment by Sweetchuck** [comment]
Az jó, hogy ennek az issue-nak konkrétan az a feladata, hogy "a szótár kitakarítása" és nem több, de szerintem ön magában nem rakható ki az élesre oldalra, mert akkor lehet választani olyat hogy:
Drupal verzió: 7
Modul: imagecache
Ami értelmetlen. (Hacsak nem azt kérdezi, hogy mikor lesz belőle stabil D7 upgrade. (Tekintve, hogy D6-hoz sincs stabil, nem is tudom mit gondoljak :-) ))

**Comment by tanarurkerem** [comment]
https://www.drupal.hu/admin/structure/views/view/_res_termek emitt egy view

**Comment by tanarurkerem** [comment]
sweetchuk, én mondom egyetértek ezzel, de attól még használható marad, ha valaki néha baromságot állít be.

**Comment by tanarurkerem** [comment]
https://www.drupal.hu/admin/structure/taxonomy/tisztitotuz

Na akinek van kedve ideje, az törölheti.

**Comment by tanarurkerem** [comment]
Szerintem zárható.

A fenti view tobható később
