### ISSUE TITLE
Egyéb, nem sürgős modulok frissítése

### ISSUE THREAD

**Issue by csakiistvan** [drupalhu/drupal.hu#192]
acquia_connector                  7.x-2.14           7.x-2.15          Frissítés elérhető
 Administration menu (admin_menu)  7.x-3.0-rc4        7.x-3.0-rc5       Frissítés elérhető
 Panels (panels)                   7.x-3.4            7.x-3.5           Frissítés elérhető
 Mollom (mollom)                   7.x-2.12           7.x-2.14          Frissítés elérhető
 Token (token)                     7.x-1.5            7.x-1.6           Frissítés elérhető

**Comment by Sweetchuck** [comment]
Ezt lezárom és minden modulnak külön issue-t hozok létre mert ez így sose lesz bemergelve
