### ISSUE TITLE
További, modulokat kell frissítéseni, developer szükséges

### ISSUE THREAD

**Issue by csakiistvan** [drupalhu/drupal.hu#193]
Az alábbi modulokat még frissíteni javasolt, ebbe nem futnék neki, developer kellene ide.

 Memcache (memcache)               7.x-1.3            7.x-1.5           Frissítés elérhető
 Search API (search_api)           7.x-1.13           7.x-1.15          Frissítés elérhető
 Solr search (search_api_solr)     7.x-1.6            7.x-1.8           Frissítés elérhető

**Comment by Sweetchuck** [comment]
Ezt lezárom és minden modulnak külön issue-t hozok létre mert ez így sose lesz bemergelve
