### ISSUE TITLE
Nem tölt be az eseményeknél a térkép

### ISSUE THREAD

**Issue by csakiistvan** [drupalhu/drupal.hu#196]
Esemény típusú tartalmaknál a térkép, ami a "Well Known Text" mező kitöltése után jelenne, sajnos az éles oldalon nem jelenik meg, JS errort látok a consoleban.

Példa kód a fieldbe: POINT (19.0625317 47.5100594)
Példa esemény tartalom: https://www.drupal.hu/node/21101

Ugyanez a tartalom localban megfelelően jelenik meg, tréképpel együtt ([kép](https://www.evernote.com/l/AA32n3HXwu5KSpJ2KkeNTQ0Pr9_auC_5mIA)).

Gyanítom hogy a drupal.hu https elérése lehet a probléma, kepcsolódó dorg issue talán ez lehet https://www.drupal.org/node/1458930

**Comment by tanarurkerem** [comment]
Azt írják, hogy a javascript az nem fog jönni https-ről, de a képek már igen. Szóval annyit kéne csinálni, hogy le kéne tölteni a js-t és nekünk hosztolni.

Itt le is van írva, hogy hogyan. Libraries modul és egy drush parancs:
https://www.drupal.hu/admin/structure/openlayers

**Comment by Sweetchuck** [comment]
30-40 percnyi hiba keresés után, bátran kimerem jelenteni, hogy bugos az openlayers modul. :-)

0. `drush dl-openlayers` szépen működik. 
0. Aztán az OpenLayers admin felületén át kell állítani a _OpenLayers source type_ mezőt _Internal_ -ra
0. A megjelenő _OpenLayers internal source variant_ rádiógomboknál nagyon kedvesen írja, hogy az _Original_ -on kívül ne is próbálkozz mással, mert úgy sem fog működni. Erre az ember nyilván az _Original_ -t fogja választani. 
0. Viszont pont az _Original_ az egyetlen ami működik, az összes többi betölti azt amit az _Original_ -nak kéne.

Az [openlayers_libraries_info()](http://cgit.drupalcode.org/openlayers/tree/openlayers.module?h=7.x-2.x#n1512) -ban nincsen definiálva `original`
Viszont a [openlayers_include()](http://cgit.drupalcode.org/openlayers/tree/openlayers.module?h=7.x-2.x#n95) kizárólag az `original` variánst hajlandó betölteni.

**Comment by Sweetchuck** [comment]
Még lehet, hogy ma csinálok PR-t

**Comment by csakiistvan** [comment]
Kész, köszönöm a munkát
https://stage.drupal.hu/node/21101

**Comment by csakiistvan** [comment]
működik, megjelennek a navigációk is a térképen,
https://dev.drupal.hu/node/21101

**Comment by tanarurkerem** [comment]
Ez szépen megy a stage-en.
