### ISSUE TITLE
Ne keressen az l10n_update modul fordításokat a custom modulokhoz

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#204]
Ne keressen az l10n_update modul fordításokat az egyedi fejlesztésű modulokhoz, mert úgysem fog találni.

Frissíteni kell az l10n_update modult a 2.x-es ágra, hogy lehessen használni a [interface translation project](http://cgit.drupalcode.org/l10n_update/tree/README.txt#n137) opciót.

**Comment by Sweetchuck** [comment]
Pici probléma, hogy a features újra generáláskor elveszik ez az információ a *.info fájlból.
most azt keresgélem, hogy mit lehet ez ellen tenni.

**Comment by Sweetchuck** [comment]
A features modul [egyik bugja](https://www.drupal.org/node/2559851) miatt veszik el az információ.
Valószínűleg a `hook_system_info_alter()`-rel meg lehet kerülni a problémát.

**Comment by csakiistvan** [comment]
Mi lenne ha az egyedi modulok/features -ök meg se jelennének az admin/reports/updates oldalon? Hisz semmi értelme amúgy, vagy ez másik issue?

**Comment by Sweetchuck** [comment]
Ez az issue arról szól, hogy a custom modulokhoz ne keressen fordításokat a localize.drupal.org-on
a #202 pedig arról, hogy ne keressen frissítéseket az updates.drupal.org-on.
