### ISSUE TITLE
View calendar - hiányzó plugin

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#216]
Ezzel a view-val van valami probléma `?q=admin/structure/views/view/calendar/edit`

__Formátum:Hiányzó stílusbővítmény__

Egyáltalán az is kérdéses, hogy használjuk-e valahol. (valószínűleg igen, de én nem tudok róla.)

**Comment by csakiistvan** [comment]
Szerintem ezt sehol nem használjuk, sem a naptár funkciót. Javaslom ennek ideiglenes törlését, ha kell naptár akkor megoldjuk majd.

**Comment by Sweetchuck** [comment]
Ezt a plugint a _calendar_ modul szolgáltatta, viszont a `git log` soha nem látta ezt a modult.
A `{system}` tábla szerint a _calendar_ modulból utoljára a _6.x-2.4_-es verzió volt bekapcsolva.
Más szóval ezek a _notice error_-ok már jönnek egy ideje.
Jellemzően a _feature recreate_ oldal tetejét díszíti 16 hiba üzenet.

Írhatok rá egy `hook_update_N()`-t is, de egyszerűbb lenne az éles oldalon kézzel törölni ezt a view-t.

**Comment by Sweetchuck** [comment]
Végül kézzel törölve lett.
