### ISSUE TITLE
dev és staging környezetek elrejtése robotok elől

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#223]
_Dev_ és _staging_ környezeteket jó lenne elrejteni a kereső robotok elől.

https://docs.acquia.com/articles/password-protect-your-non-production-environments-acquia-hosting

**Comment by csakiistvan** [comment]
Remek ötlet

**Comment by csakiistvan** [comment]
Nekem a dev site továbbra is simán bejön, mit kell még tenni, hogy kell tesztelni?

**Comment by Sweetchuck** [comment]
# Tesztelés lépései

0. El kell kell pusholni a branchet az Acquia git repóba. (Már ott van csak, --force pushal frissíteni, mert közben rebaseltem)
0. Az insight.acquia.com admin felületen átállítani, hogy ezt a kódbázist használja a _dev_ környezet.
0. Az insight.acquia.com felületen az _prod_-ról át kell húzni a DB-t a _dev_-re. (Ilyenkor fognak lefutni az Acquia cloud hook-ok, és bekapcsolják a _shield_ és _drupalhu_shield_settings_ modulokat)

**Comment by csakiistvan** [comment]
működik

**Comment by tanarurkerem** [comment]
Miért kellett rebaselni???
Hogyan tesztelem?

**Comment by Sweetchuck** [comment]
Minden feature branchemet a _dev_-ből indítottam, miután a István az egyiket beolvasztotta a _dev_-be, az összes többit rebase-eltem a frissített _dev_ -re.

Kb ez van leírva a README-md-ben is (csak ott hibásan, mert azt írja, hogy a _stable-acquia_ branch-re kell rebase-elni (10, 11, és 12-es pont))

**Comment by tanarurkerem** [comment]
rebase: ok, ez van akkor.
 
Tesztelni hogyan tudom? Mert most a stage kér egy jelszót, ez elég? Mert akkor oké ez az issue.

**Comment by tanarurkerem** [comment]
jah... látom fent írtad, csak vak vagyok. :) hát azt most nem fogom tesztelni, mert picit bonyinak tűnik nekem.

**Comment by Sweetchuck** [comment]
Igen. Az a lényeg, hogy az alábbi linkek kérjenek HTTP hitelesítést
* `https://druphungarydev.prod.acquia-sites.com`
* `https://druphungarystg.prod.acquia-sites.com`
* `https://dev.drupal.hu`
* `https://stage.drupal.hu`

Viszont a `www.drupal.hu` ne kérjen HTTP hitelesítést

**Comment by tanarurkerem** [comment]
végignyomkodtam, mindegyik kér. (tested label-t megpróbáltam rárakni az issuera de nem ment..)

**Comment by csakiistvan** [comment]
@tanarurkerem most próbáld meg a cimkét rátenni, most létrehoztam

**Comment by tanarurkerem** [comment]
okézsoké
