### ISSUE TITLE
Az DB tisztító scriptből az SQL block kimozgatása külön fájlba

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#237]
A DB tisztító fájlban egy kis refactor növelné az olvashatóságot.
`hooks/dev/post-db-copy/db-scrub.sh`
Van egy nagy
``` bash
(cat <<EOF
-- SQL
EOF
) | drush ah-sql-cli
```

részünk, amiben van 
``` sql
UPDATE users SET pass='$S$DMXNF9w9lpy9xux.OJ5kyNgzh5hEerBjdHhF5v.BH7Ekp7PMJsc7'`
```
Tehát a Bash vagy Sh megpróbálja értelmezni a `$foo` részeket.
Picivel jobb lenne a `(cat <<'EOF'` használata.

De még jobb lenne az egész SQL-t külön fájlba rakni, és akkor vagy `cat foo.sql | drush ah-sql-cli`
vagy `drush ah-sql-cli < foo.sql`

Ha külön fájlban van az SQL akkor lenne hozzá syntax highlight.

**Comment by aboros** [comment]
tök jó javaslat! megpróbálom megcsinálni. én írtam a db-scrub.sh, így volt az acquia hooks dokumentációban a példa, ahogy a mostani.

**Comment by Sweetchuck** [comment]
Szeretnék csinálni egy scriptet ami az adatbázis publikálást könnyítené meg, és azzal együtt ezt is megcsinálom. Ezért rendeltem magamhoz ezt az issue-t
