### ISSUE TITLE
Modul frissítés - Google Analytics-7.x-1.4

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#241]
A jelenleg használt _Google Analytics-7.x-1.4_ frissítése a legújabb verzióra.

A legújabb verzió = 7.x-2.1
> Ez a frissítés egy nagyobb verzióváltás, ami azt jelenti, hogy a mostani verzióval nem lesz visszafelé kompatibilis. Ilyen esetben ajánlott a kiadási információk szokásosnál alaposabb tanulmányozása.

**Comment by Sweetchuck** [comment]
Localhost-on összehasonlítottam a 1.4 és az update utáni 2.1-es beállításokat az admin felületen és csak 1 dolgot találtam ami különbözik.
Olyan mintha a 1.4-ben lévő _Egyéni változók_ résznek nem lenne pontos megfelelője a 2.1-ben.
Leginkább a _Custom metrics_ és a _Custom dimensions_ hasonlít.
https://www.drupal.hu/admin/config/system/googleanalytics#edit-googleanalytics-custom-var

**Comment by snufkin** [comment]
Mergaltam, az admin felulet valoban valtozott, de ha jol lattam a kodbol, akkor az update hook elintezi a valtozok migralasat.
