### ISSUE TITLE
Letöltés szekcióban nem jelent meg a Drupal 8

### ISSUE THREAD

**Issue by csakiistvan** [drupalhu/drupal.hu#244]
https://www.drupal.hu/ fejlécében, a letöltés szekcióban nem jelent meg a Drupal 8 linkje. A drupal 6-nak el kellene ugyanakkor tűnnie, ha a d8 megjelenik.

**Comment by boobaa** [comment]
A D8 linket én is hiányolom, viszont a D6 még vagy három hónapig támogatott marad, tehát nem biztos, hogy muszáj lenne azt a linket eltüntetni.

**Comment by Sweetchuck** [comment]
Ez most nálam így néz ki. Lesz még vele egy csomó probléma, de legalább megjelenik a D8-as letöltés link.

![drupalhu-issue-244](https://cloud.githubusercontent.com/assets/591103/11920863/1d470240-a77a-11e5-98b3-0b6a47a8ef49.png)

**Comment by aboros** [comment]
nekem nagyon tetszik @Sweetchuck tök szuper!

**Comment by csakiistvan** [comment]
mit jelent ez pontosan? "Lesz még vele egy csomó probléma"

**Comment by Sweetchuck** [comment]
D8-hoz nem kell külön fordítás, mert telepítéskor is letölti vagy később a nyelv engedélyezésekor is letölti.

Amikor majd levesszük a D6-os letöltési linkeket akkor majd kell egy kicsit a CSS-t macerálni.
Jelenleg a D8-as letöltési link 3 szám és 2 pont, de majd ha 4 számjegy lesz benne, akkor már nem fog kiférni. 8.0.1 vs 8.0.10 vs 8.22.22

**Comment by csakiistvan** [comment]
Rendben, köszi
