### ISSUE TITLE
Non-UTF8 karakterek eltörik a SearchAPI indexelést

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#332]
Jelenség

A SearchAPI indexelés nem megy végig.
2 hiba üzenet a Drupal log-ban
egyik:
```
Drupal\search_api_solr\SearchApiSolrException while indexing: Solr endpoint http://127.0.0.1:8983/solr/drupalhu8__default/ unreachable. in Drupal\search_api_solr\SolrConnector\SolrConnectorPluginBase->handleHttpException() (line 818 of /.../docroot/modules/contrib/search_api_solr/src/SolrConnector/SolrConnectorPluginBase.php).
```
a másik
```
Drupal\search_api\SearchApiException while trying to index items on index Acquia Search Solr Index: Solr endpoint http://127.0.0.1:8984/solr/drupalhu8__default/ unreachable. in Drupal\search_api_solr\Plugin\search_api\backend\SearchApiSolrBackend->indexItems() (line 717 of /.../docroot/modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php)
```

Solr log:
```
ERROR - 2019-10-08 21:04:42.060; org.apache.solr.common.SolrException; org.apache.solr.common.SolrException: Illegal character ((CTRL-CHAR, code 31))
```
A karakter kód nem mindig ugyan az.

Például ez az egyik node aminek az indexelésénél eltörik.
https://www.drupal.hu/forum/furcsa-karakterek-fogadnak

**Comment by Pandelon** [comment]
több mint 10 éves tartalom, D5, gyomláljuk ki szerintem

**Comment by Sweetchuck** [comment]
Ilyen karaktereket bárki beírhat bármikor. Azt kell megoldani, hogy ez ne okozzon problémát.

**Comment by Sweetchuck** [comment]
Egyelőre ez a megoldás, amíg nincsen jobb
https://github.com/drupalhu/drupal.hu/blob/4ed53dc771e453a5c2cc6946ef4235d093d95234/docroot/modules/custom/app_dc/config/install/migrate_plus.migration.app_legacy__comment__forum.yml#L75
