### ISSUE TITLE
Kapcsolat felvételi űrlap

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#350]
Jelenlegi weboldalon van [Kapcsolat felvételi űrlap](https://drupal.hu/kapcsolat).
Ránézésre ez a Drupal alap „contact” moduljával van megvalósítva.

Én nem találtam meg, hogy hol van rá link menüből (fejléc lábléc, ilyesmi).
Viszont néhány node:body-ból van rá link.
Egy linket illene kirakni legalább a láblécbe.

Szerintem jó lesz ugyan ez a funkcionalitás az új oldalon is.
Spam védelem biztos nem ártana.
Illetve a webform jöhet még szóba. Kérdés az, hogy kell-e az nekünk ehhez a feladathoz vagy majd később?

**Comment by aboros** [comment]
Szerintem nem kell webform, működjön a core contact modullal, legyen link a láblécben és jók vagyunk.
